import Link from "next/link";

export default function ApiTermsPage() {
  return (
    <main className="min-h-dvh bg-[#0a0a0a] pt-14">
      <div className="max-w-2xl mx-auto px-4 py-10">
        <div className="mb-8">
          <div className="flex items-center gap-2 text-sm text-white/40 mb-4">
            <Link href="/developers" className="hover:text-white transition-colors">Developers</Link>
            <span>/</span>
            <span>API Terms</span>
          </div>
          <h1 className="text-white text-3xl font-bold tracking-tight">API Terms of Service</h1>
          <p className="text-white/40 text-sm mt-2">Last updated: April 2026</p>
        </div>

        <div className="space-y-8 text-white/70 text-sm leading-relaxed">

          <section>
            <h2 className="text-white font-semibold text-base mb-3">1. Acceptance</h2>
            <p>By creating an API key or making any request to the Charta Alba API, you accept these API Terms of Service in addition to the general <Link href="/terms" className="text-white/80 hover:text-white underline transition-colors">Terms of Service</Link>. If you do not agree, do not use the API.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">2. Attribution Requirement</h2>
            <p className="mb-2">Any product, application, or service that displays data obtained from the Charta Alba API must include a visible attribution statement. Acceptable forms include:</p>
            <ul className="list-disc list-inside space-y-1 text-white/50 ml-2">
              <li>"Powered by <a href="https://chartaalba.com" className="text-white/70 hover:text-white underline transition-colors">Charta Alba</a>"</li>
              <li>"Research data via Charta Alba API"</li>
              <li>The Charta Alba logo with a link to chartaalba.com</li>
            </ul>
            <p className="mt-2">Attribution must be reasonably visible to end users of your product — not buried in a footer no one reads.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">3. Prohibited Uses</h2>
            <p className="mb-2">You may not use the Charta Alba API to:</p>
            <ul className="list-disc list-inside space-y-1.5 text-white/50 ml-2">
              <li><strong className="text-white/70">Resell raw data.</strong> You may not sell, sublicense, or redistribute API responses as a standalone data product or data feed.</li>
              <li><strong className="text-white/70">Build competing research feeds.</strong> You may not use the API to build a product whose primary function is a research paper discovery or summary feed that competes directly with Charta Alba.</li>
              <li><strong className="text-white/70">Share API keys.</strong> API keys are personal and non-transferable. You must not share your key with third parties or embed it in public client-side code.</li>
              <li><strong className="text-white/70">Circumvent rate limits.</strong> You may not use multiple keys to bypass tier limits, rotate keys to avoid tracking, or otherwise game the rate-limiting system.</li>
              <li><strong className="text-white/70">Scrape at scale without permission.</strong> Automated bulk extraction beyond normal API usage patterns requires prior written approval.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">4. AI Disclosure</h2>
            <p>Paper summaries, TLDRs, and ELI5 explanations returned by the API are generated by AI (Anthropic Claude). If you display these summaries to end users, you must disclose that they are AI-generated. We do not guarantee their accuracy, completeness, or fitness for any purpose, including academic or commercial research decisions.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">5. Free Tier Restrictions</h2>
            <p>The Free tier (0 USD/month) is licensed for <strong className="text-white/70">non-commercial use only</strong>. This includes personal projects, academic research, and internal prototypes that do not generate revenue. If you are using the API commercially, you must be on a paid plan. Charta Alba reserves the right to revoke free-tier access for commercial use without notice.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">6. Academic Content & DMCA</h2>
            <p className="mb-2">Paper metadata (titles, abstracts, authors, arXiv IDs) is sourced from arXiv under their terms of use. AI-generated summaries are created by Charta Alba and are our intellectual property. The following applies:</p>
            <ul className="list-disc list-inside space-y-1 text-white/50 ml-2">
              <li>Paper abstracts are the intellectual property of the respective authors and are reproduced under arXiv's non-exclusive distribution licence.</li>
              <li>If you believe API responses infringe your copyright, contact us at <a href="mailto:dmca@chartaalba.com" className="text-white/70 hover:text-white underline transition-colors">dmca@chartaalba.com</a> with full details of the alleged infringement.</li>
              <li>We will respond to valid DMCA takedown notices within 10 business days.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">7. Abuse & Revocation</h2>
            <p>We reserve the right to suspend or permanently revoke API access for any violation of these terms or abuse of the platform. For first-time, non-egregious violations, we will provide a <strong className="text-white/70">24-hour notice and cure period</strong> before revocation. Egregious violations (scraping, key sharing at scale, competing product) may result in immediate revocation without notice.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">8. Service Level & Uptime</h2>
            <p>We do not guarantee any specific uptime SLA for free or paid tiers below Enterprise. We aim for 99.5% monthly availability. Planned maintenance will be announced via the Charta Alba status page. For Enterprise SLAs, contact <a href="mailto:support@chartaalba.com" className="text-white/70 hover:text-white underline transition-colors">support@chartaalba.com</a>.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">9. Billing & Refunds</h2>
            <p>Paid plans are billed monthly or annually in advance. Request limits reset on the first day of each calendar month UTC. We do not offer prorated refunds for partial months. Annual plans may be refunded within 14 days of first payment if the API has not been used in production. Contact <a href="mailto:support@chartaalba.com" className="text-white/70 hover:text-white underline transition-colors">support@chartaalba.com</a> for billing disputes.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">10. Changes to the API</h2>
            <p>We will provide at least 30 days' notice before removing or breaking any endpoint. New endpoints, fields, and query parameters may be added without notice. We version the API (currently v1) and will maintain v1 for at least 12 months after any v2 launch.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">11. Disclaimer of Warranties</h2>
            <p>The API is provided "as is" without warranties of any kind. Charta Alba expressly disclaims all warranties of merchantability, fitness for a particular purpose, and non-infringement. AI-generated summaries are informational only and must not be relied upon for academic citation, medical, legal, or financial decisions.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">12. Governing Law</h2>
            <p>These API Terms are governed by the laws of the State of Delaware, USA, without regard to conflict-of-law principles. Any disputes shall be resolved by binding arbitration in Delaware. You waive the right to participate in a class action lawsuit arising from API use.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">13. Contact</h2>
            <p>For API-related questions, abuse reports, or DMCA notices: <a href="mailto:api@chartaalba.com" className="text-white/80 hover:text-white underline transition-colors">api@chartaalba.com</a></p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/8 flex flex-wrap gap-4 text-sm">
          <Link href="/developers" className="text-white/40 hover:text-white transition-colors">Developer Portal</Link>
          <Link href="/developers/docs" className="text-white/40 hover:text-white transition-colors">API Docs</Link>
          <Link href="/terms" className="text-white/40 hover:text-white transition-colors">General Terms</Link>
          <Link href="/privacy" className="text-white/40 hover:text-white transition-colors">Privacy Policy</Link>
        </div>
      </div>
    </main>
  );
}
